version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  target-branch: dev
  allow:
  - dependency-type: direct
  - dependency-type: indirect
